language: java
jdk:
- oraclejdk8
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script: 
  - '[ ${TRAVIS_PULL_REQUEST} = ''false'' -a ${TRAVIS_BRANCH} = ''master'' ] && (cd powerunit && mvn clean install site -Psite --settings ../target/travis/settings.xml) || echo ''Ignore'' '
  - '[ ${TRAVIS_PULL_REQUEST} = ''false'' -a ${TRAVIS_BRANCH} != ''master'' ] && (cd powerunit && mvn clean install --settings ../target/travis/settings.xml) || echo ''Ignore'' '
